config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers, only: [:new, :create, :show, :index] do

    member do
      get :success
    end
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index] do
    member do # member when you want id in link
      get :success
    end
  end
end

# collection /bookings/success

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :begin_on, presence: true
  # validates :end_smaller_than_begin?
  validates :end_on, presence: true #end_on > begin_on

 # def end_smaller_than_begin?
  #  if begin_on > end_on
   #   errors.add(:begin_on, 'end date can not be before begin date')
    #end
  #end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_one_attached :photo

  validates :title, :description, :category, :price, :location, :pick_up_at, presence: true
  validates :category, inclusion: { in: ['Gym equipment', 'Ball sports', 'Racket sports', 'Water sports', 'Winter sports', 'Fighting sports', 'Yoga equipment', 'Other'] }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :offers, through: :bookings, dependent: :destroy # all offers where I am the buyer
  has_many :host_offers, class_name: 'Offer', foreign_key: :host_id #all offers where I am the host
  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  include Pundit
  
   # Pundit: white-list approach.
   after_action :verify_authorized, except: :index, unless: :skip_pundit?
   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
 
   # Uncomment when you *really understand* Pundit!
   # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
   # def user_not_authorized
   #   flash[:alert] = "You are not authorized to perform this action."
   #   redirect_to(root_path)
   # end
 
   private
 
   def skip_pundit?
     devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
   end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
    # All Bookings that exist in my app
    # Filter into three categories:
    # => Incoming Bookings: Bookings for my for created offer // offer.user = me
    user = current_user
    @offers = user.host_offers
    # => Outgoing Bookings: Bookings that I created // booking.user = me
    @bookings = user.bookings
    #user = current_user
    #Booking.where(user_id: user)
    #@bookings.user =
    # => Irrelevant Bookings: Neither for my offer and aren't my bookings // anything else
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @offer = Offer.find(params[:offer_id])
    start_date = params[:booking][:begin_on].split[0].to_date
    end_date = params[:booking][:begin_on].split[2].to_date
    @booking = Booking.new(begin_on: start_date, end_on: end_date)
    @booking.offer = @offer
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to success_booking_path(@booking)
    else
      render :new
    end
  end

  def success
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:begin_on, :end_on)
  end
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @offers = policy_scope(Offer)

    sql_query = "category ILIKE :query OR title ILIKE :query OR description ILIKE :query"
    if params[:query].present?
      @offers = Offer.where(sql_query, query: "%#{params[:query]}%")
    else
      @offers = Offer.all
    end

    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: 
          { offer: offer }),
        image_url: helpers.asset_url('marker.png')
      }
    end
  end

  def show
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.host = current_user
    authorize @offer
      if @offer.save
        redirect_to success_offer_path(@offer)
      else
        render :new
      end
  end

  def success
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :category, :price, :location, :pick_up_at, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= render 'shared/navbar' %>
<div class="content">
<div class="container mt-9">
  <div class="row justify-content-center">
    <div class="col-lg-10">
        <div class="bookings"><h1>My offers</h1></div>
            <div class="cards-dashboard">
            <% @offers.each do |offer| %>
              <div class="card" style="width: 18rem;">
              <%= link_to offer_path(offer) do %>
              <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key, class: "card-img-top" %>
              <% else %>
              <% placeholder_url = "https://images.unsplash.com/photo-1526401485004-46910ecc8e51?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" %>
              <%= image_tag placeholder_url, class: "card-img-top" %>
              <% end %>
              <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= offer.title %></h5>
                  <hr>
                  <h5 class="price"><%= offer.price %>€</h5>
                </div>
              </div>
            <% end %>
        </div>
            <div class="bookings"><h1>My bookings</h1></div>
            <div class="cards-dashboard">
            <% @bookings.each do |booking| %>
              <div class="card" style="width: 18rem;">
              <%= link_to offer_path(booking.offer) do %>
              <% if booking.offer.photo.attached? %>
              <%= cl_image_tag booking.offer.photo.key,class: "card-img-top" %>
              <% else %>
              <% placeholder_url = "https://images.unsplash.com/photo-1526401485004-46910ecc8e51?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" %>
              <%= image_tag placeholder_url, class: "card-img-top" %>
              <% end %>
              <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= booking.offer.title %></h5>
                  <hr>
                  <h5 class="price"><%= booking.offer.price %>€</h5>
                </div>
              </div>
            <% end %>
        </div>
  </div>
  </div>
</div>

</div>

<%= render 'shared/footer' %>

app/views/bookings/new.html.erb
<div class="container mh-100 w-75 shadow p-3 mb-5 bg-white rounded">
  <div class="row m-5">

   <div class="col-sm m-5">
      <h2 class="mb-4">Book your equipment!</h2>
      <%= simple_form_for [@offer, @booking] do |f| %>
        <%= f.input :begin_on, as: :string, input_html: {class: "datepicker"}, label: "Choose the dates" %>
        <%= f.submit 'Reserve', class: 'btn btn-primary my-3' %>
      <% end %>
   </div>

    <div class="card-trip col-sm m-5">
      <%= cl_image_tag @offer.photo.key, crop: :fill%>
      <div class="card-trip-infos">
        <div>
          <h2><%= @offer.title %></h2>
        </div>
        <h2><%= "#{@offer.price} € / day" %></h2>
      </div>
    </div>

  </div>
</div>
  

app/views/bookings/success.html.erb
<%= render 'shared/navbar' %>
<div class="container w-75 shadow-none p-3 my-5 rounded">
  <div class="text-center m-5">
    <h1 class="mb-5">Congratulations!</h1>
    <iframe src="https://giphy.com/embed/5orToQ5JFECis" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/coca-cola-goal-gol-yass-5orToQ5JFECis"></a></p>
    <h4>Your booking was successful!</h4>
    <div class="m-5">
      <h5><%= "Pick it up at: #{@booking.offer.pick_up_at.strftime("%-d.%-m.%y - %H:%M")}" %></h5>
      <h5><%= "#{@booking.offer.location}" %></h5>
    </div>
     <div>
      <%= link_to 'Go to your Dashboard', bookings_path, class: 'btn btn-ghost' %>
    </div>
    <div class="m-2">
      <%= link_to 'Back to all sports equipments', offers_path, class: 'btn btn-ghost'%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSporte</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/offers/_info_window.html.erb
<h4><%= offer.title %></h4>
<p><%= offer.location %></p>

app/views/offers/index.html.erb
<%= render 'shared/navbar' %>

  <div class="main-container">
    <div class="cards-map">
      <div class="grid-system">
        <div class="title"><h1>All offers</h1></div>
        <div><%= link_to 'Add an offer', new_offer_path, class: 'btn-filled m-5' %></div>
        
          <div class="row mx-5 mt-5">
            <div class="col w-25">
              <%= form_tag offers_path, method: :get do %>
                <%= text_field_tag :query,
                params[:query],
                class: "form-control lg",
                placeholder: "Search for equipment"
              %>
            </div>
            <%= submit_tag "Search", class: "btn btn-ghost mr-3" %>
            <% end %>
          </div>
        
          
            <div class="cards m-5">
            <% @offers.each do |offer| %>
              <div class="card" style="width: 18rem;">
              <%= link_to offer_path(offer) do %>
              <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key,class: "card-img-top" %>
              <% else %>
              <% placeholder_url = "https://images.unsplash.com/photo-1526401485004-46910ecc8e51?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" %>
              <%= image_tag placeholder_url, class: "card-img-top" %>
              <% end %>
              <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= offer.title %></h5>
                  <hr>
                  <h5 class="price"><%= offer.price %> €</h5>
                </div>
              </div>
            <% end %>
            </div>
        </div>
      </div>
    
    <div id="map"
     style="width: 100%; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

  </div>

<%= render 'shared/footer' %>

app/views/offers/new.html.erb
<div class="container w-75 shadow-sm p-3 mb-5 bg-white rounded">
  <div class="my-5">
    <h1 class="d-flex justify-content-center">Share your sports equipment</h1>
    <h2 class="d-flex justify-content-center">We need some more details</h2>
  </div>
  <div class="d-flex justify-content-center mb-5">
    <%= simple_form_for(@offer) do |f| %>
      <%= f.input :title, label: "Name your sports equipment?" %>
      <%= f.input :description, as: :text, label: "Add some details: Is the item in good shape? Why do you want to rent it out? etc." %>
      <%= f.input :price, label: "What's the price per day" %>
      <%= f.input :category, as: :radio_buttons, collection: ['Gym equipment', 'Ball sports', 'Racket sports', 'Water sports', 'Winter sports', 'Fighting sports', 'Yoga equipment', 'Other'], label: 'Choose a category'  %>
      <%= f.input :location, label: "Add address where item can be picked up?" %>
      <%= f.input :pick_up_at, as: :string, input_html: {class: "date"}, label: "Choose the dates" %>
      <%= f.input :pick_up_at, as: :time, label: "Pick-up time?" %>
      <%= f.input :photo, as: :file, label: 'Add a picture to your item' %>
      <%= f.submit 'Create Offer', class: 'btn btn-filled-new my-4 w-100'%>
    <% end %>
  </div>
</div>

app/views/offers/offers.html.erb
<h1>All offers</h1>

<% @offers.each do |offer| %>
<div>
  <td><%= offer.title %> <%= offer.description %> <%= offer.category %> <%= offer.price %> <%= offer.location %> <%= offer.pick_up_at %></td>
</div>

<% end %>

app/views/offers/show.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5 w-75 p-5 ">
  <div class="mt-5 mx-5 px-3">
    <h1><%= @offer.title %></h1>
    <h3 class="p-2"><%= @offer.category %></h3>
  </div>
  <hr>
  <div class="cards m-5">
    <div class="col-sm mr-5">
      <%= cl_image_tag @offer.photo.key, height: 250, crop: :fill, class: "item-image" %>
    </div>

    <div class="col-sm">
      <div class="card-category mb-2">
        <p>Pick-up time</p>
        <p><%= "#{@offer.pick_up_at.strftime("%d.%m.%Y - %H:%M")}" %></p>
        <h3><%= "#{@offer.price} €/ day" %></h3>
        <%= link_to 'Book now', new_offer_booking_path(@offer), class: 'btn btn-black my-3'%>
      </div>
    </div>
  </div>

  <div class="m-5 px-3">
    <p><%= @offer.description %></p>
  </div>
  <hr>
  <div class="mx-5 mt-5">
    <%= link_to 'Back to all offers', offers_path, class: 'btn btn-ghost px-3'%>
  </div>
</div>

app/views/offers/success.html.erb
<%= render 'shared/navbar' %>
<div class="container w-75 shadow-none p-3 my-5 rounded">
  <div class="text-center m-5">
    <h1>Congratulations!</h1>
    <h4 class="mb-5">You successfully created your offer!</h4>
    <iframe src="https://giphy.com/embed/Q9FGOQewX92eRRO9Qi" width="480" height="269" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/wwe-wrestling-raw-monday-night-Q9FGOQewX92eRRO9Qi"></a></p>
    <div>
      <%= link_to 'Go to your Dashboard', bookings_path, class: 'btn btn-ghost' %>
    </div>
    <div class="m-5">
      <%= link_to 'Browse sports equipments', offers_path, class: 'btn btn-ghost'%>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<div class="wrapper">
  <header>
  <div class="banner-landing">
    <div class="banner-content">
        <div id="banner-title"><h1>No sport equipment ? No Problem ! </h1></div>
        <div class="button btn-advanced">
            <svg>
                <rect x="0" y="0" fill="none" width="100%" height="100%"/>
            </svg>
            <%= link_to 'Explore', offers_path, class: "button text"%>
        </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-info">
    <a href="#"><p class="mb-0">Blog</p></a>
    <a href="#"><p class="mb-0">Privacy</p></a>
    <a href="#"><p class="mb-0">Company details</p></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav>
    <div class="menu">
    <div class="menu-icon">
        <i class="fas fa-spa"></i>
        <%= link_to "Sporte", root_path, class: "links-home"%>
    </div>
    <div class="menu-list">
        <ul>
            <%= link_to "Create offer",  new_offer_path, class: "link-offer"%>
            <li>
                <% if user_signed_in? %>
                <div class="user d-flex justify-content-between items-align-center">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            My account
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <%= link_to 'My Dashboard', bookings_path, class: "dropdown-item links-dropdown" %>
                            <a class="dropdown-item" href="#">Settings</a>
                            <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item links-dropdown", method: :delete%>
                        </div>
                    </div>
                    <img class="avatar m-3" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
                </div>
                <% else %>
                <%= link_to "Sign up", new_user_registration_path, class: "links" %> |
                <%= link_to "Login", new_user_session_path, class: "links"%>
                <% end %>
            </li>
        </ul>
    </div>
    </div>
</nav>